# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ed1fd71ef003c4f5ac7e58ebe051f618a71eb0b3c216ae338901e2857d636ed4c4ff501c78e131f99a9c14f779f7259d9fa7f5be73037f68d28ee3af2751676

test:
  secret_key_base: 507312944d26bc32232bff7d0069af3af4d931fab770ee462591e9bde1c77b8febc2bd87af055d295d45dcccec816292f76bf692aca64cefa03b1bf743232710

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
